version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - adrenalux-network

  app:
    build: .
    container_name: express_server
    depends_on:
      - db
    environment:
      DB_USER: ${DB_USER}
      DB_HOST: ${DB_HOST}  
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: 5432
    ports:
      - "3000:3000"
    networks:
      - adrenalux-network
    command: ["sh", "-c", "npx drizzle-kit migrate && node ./api/test/loadFixtures.js && node server.js"]

networks:
  adrenalux-network:
    driver: bridge

volumes:
  pg_data:
